
var numPlayers = 4;
var p = [
    {
        player: null,
        TURBO_MULTIPLIER: 3,
        HORIZONTAL_SPEED: 40,
        VERTICAL_SPEED: 12,
        GRAVITY: 50,
        FULL_SPEED: 200,
        SIDE_DECAY: 1.2,
        DOWN_DECAY: 1.06,
        JUMP_POWER: 1600,
        LENGTH_OF_TAIL: 1000,
        SPEED_OF_TAIL: 30,
        cursorsWASD: null,
        velocity: { x: 0, y: 0 },
        flipFlop: { r: false, l: false, u: false, d: false },
        turboFlipFlop: false,
        turboMultiply: 0,
        particles: null,
        emitter: null,
        keyboard: {
            up: Phaser.Input.Keyboard.KeyCodes.W,
            down: Phaser.Input.Keyboard.KeyCodes.S,
            left: Phaser.Input.Keyboard.KeyCodes.A,
            right: Phaser.Input.Keyboard.KeyCodes.D,
            fast: Phaser.Input.Keyboard.KeyCodes.Z,
            jump: Phaser.Input.Keyboard.KeyCodes.X,
        },
    },
    {
        player: null,
        TURBO_MULTIPLIER: 3,
        HORIZONTAL_SPEED: 40,
        VERTICAL_SPEED: 12,
        GRAVITY: 50,
        FULL_SPEED: 200,
        SIDE_DECAY: 1.2,
        DOWN_DECAY: 1.06,
        JUMP_POWER: 1600,
        LENGTH_OF_TAIL: 1000,
        SPEED_OF_TAIL: 30,
        cursorsWASD: null,
        velocity: { x: 0, y: 0 },
        flipFlop: { r: false, l: false, u: false, d: false },
        turboFlipFlop: false,
        turboMultiply: 0,
        particles: null,
        emitter: null,
        keyboard: {
            up: Phaser.Input.Keyboard.KeyCodes.T,
            down: Phaser.Input.Keyboard.KeyCodes.G,
            left: Phaser.Input.Keyboard.KeyCodes.F,
            right: Phaser.Input.Keyboard.KeyCodes.H,
            fast: Phaser.Input.Keyboard.KeyCodes.V,
            jump: Phaser.Input.Keyboard.KeyCodes.B,
        },
    },
    {
        player: null,
        TURBO_MULTIPLIER: 3,
        HORIZONTAL_SPEED: 40,
        VERTICAL_SPEED: 12,
        GRAVITY: 50,
        FULL_SPEED: 200,
        SIDE_DECAY: 1.2,
        DOWN_DECAY: 1.06,
        JUMP_POWER: 1600,
        LENGTH_OF_TAIL: 1000,
        SPEED_OF_TAIL: 30,
        cursorsWASD: null,
        velocity: { x: 0, y: 0 },
        flipFlop: { r: false, l: false, u: false, d: false },
        turboFlipFlop: false,
        turboMultiply: 0,
        particles: null,
        emitter: null,
        keyboard: {
            up: Phaser.Input.Keyboard.KeyCodes.I,
            down: Phaser.Input.Keyboard.KeyCodes.K,
            left: Phaser.Input.Keyboard.KeyCodes.J,
            right: Phaser.Input.Keyboard.KeyCodes.L,
            fast: Phaser.Input.Keyboard.KeyCodes.O,
            jump: Phaser.Input.Keyboard.KeyCodes.P,
        },
    },
    {
        player: null,
        TURBO_MULTIPLIER: 3,
        HORIZONTAL_SPEED: 40,
        VERTICAL_SPEED: 12,
        GRAVITY: 50,
        FULL_SPEED: 200,
        SIDE_DECAY: 1.2,
        DOWN_DECAY: 1.06,
        JUMP_POWER: 1600,
        LENGTH_OF_TAIL: 1000,
        SPEED_OF_TAIL: 30,
        cursorsWASD: null,
        velocity: { x: 0, y: 0 },
        flipFlop: { r: false, l: false, u: false, d: false },
        turboFlipFlop: false,
        turboMultiply: 0,
        particles: null,
        emitter: null,
        keyboard: {
            up: Phaser.Input.Keyboard.KeyCodes.UP,
            down: Phaser.Input.Keyboard.KeyCodes.DOWN,
            left: Phaser.Input.Keyboard.KeyCodes.LEFT,
            right: Phaser.Input.Keyboard.KeyCodes.RIGHT,
            fast: Phaser.Input.Keyboard.KeyCodes.END,
            jump: Phaser.Input.Keyboard.KeyCodes.PAGE_DOWN,
        },
    },
];